### ISSUE TITLE
Does not support 2 Factor Authentication

### ISSUE THREAD

**Issue by burritosoftware** [anon5r/KsGameLauncher#20]
Signing in with an account with email 2 Factor does not work. A code is sent to the email but there is no way to enter it in the app.
A workaround is to disable 2FA on the account, then sign in and launch a game. Afterwards, reenable it. However this must be done every time you want to play.

**Comment by anon5r** [comment]
@burritosoftware 
Hi, thank you for your reporting.

Yes, I have known this issue. #2 (Japanese written, but the same)

I have an idea to solve this, and will solve it in the near future.

**Comment by burritosoftware** [comment]
Yes exactly.

**Comment by anon5r** [comment]
@burritosoftware 
Support this issue next release, now you can try [beta version here](https://github.com/anon5r/KsGameLauncher/releases/tag/v1.0.1-beta)

Please let me know if you have any problems.

**Comment by burritosoftware** [comment]
@anon5r Bug: The context menu does not show any text
![image](https://user-images.githubusercontent.com/37681398/151689476-49633277-7cb9-4fe0-806b-d8e7ec002bda.png)

**Comment by anon5r** [comment]
@burritosoftware Thank you reporting.
Perhaps the language translation is not properly falling back to the English defaults.
will check this causes.
